INSERT INTO `#__pf_configs` (`id`, `config_key`, `config_value`) VALUES
(1, 'cb_integration', '0'),
(2, 'enable_captcha', '0'),
(3, 'path_upload', 'images/com_pmform'),
(4, 'allowed_extensions', 'pdf,doc,docx,zip,rar'),
(5, 'use_https', '0'),
(6, 'bypass_confirmation_page', '0'),
(7, 'fix_next_button', '0'),
(8, 'accept_term', '0'),
(9, 'article_id', '0'),
(10, 'date_format', '%d-%m-%Y'),
(11, 'currency_symbol', '$'),
(12, 'default_country', 'United States'),
(13, 'notification_emails', ''),
(14, 'admin_email_subject', 'New Payment for [FORM_TITLE]'),
(15, 'admin_email_body', '<p>Dear administrator !</p>\r\n<p>You got new payment from [FIRST_NAME] [LAST_NAME] . The payment detail is as follow : [PAYMENT_DETAIL]</p>\r\n<p>Regards,</p>\r\n<p>Company Name</p>\r\n<p> </p>'),
(16, 'user_email_subject', 'Payment for [FORM_TITLE] confirmation'),
(17, 'user_email_body', '<p>Dear [FIRST_NAME][LAST_NAME]</p>\r\n<p>Thanks for your payemnt. Your payment detail is as follow :</p>\r\n<p>[PAYMENT_DETAIL]</p>\r\n<p>Regards.</p>\r\n<p>Company name</p>'),
(18, 'user_email_body_offline', '<p>Dear [FIRST_NAME][LAST_NAME]</p>\r\n<p>Thanks for your payment . Your payment detail is as follow :</p>\r\n<p>[PAYMENT_DETAIL]</p>\r\n<p>Please send the offline payment ASAP to our bank account . Information of our bank account is as follow :</p>\r\n<p><strong>Tuan Pham Ngoc, Ngan Hang Ngoai Thuong Vietcombank, Account Number XXX045485467</strong></p>\r\n<p>We are looking forward to receiving your payment .</p>'),
(19, 'payment_approved_email_subject', 'Your Payment Form [FORM_TITLE] Completed'),
(20, 'payment_approved_email_body', '<p>Your Payment was approved !</p>'),
(21, 'donation_form_msg', '<p>Please enter information on this form to make payment for <strong>[FORM_TITLE]</strong> . The amount you need to pay is <strong>$[AMOUNT]</strong> .</p>'),
(22, 'confirmation_message', '<p>Please review the information below . If they are correct, Click "Process" button to Process payment for <strong>[FORM_TITLE] </strong>. If they are in-correct , Click on "Back" button to update the in-correct data. The amount you have to pay is <strong>[AMOUNT]</strong>.</p>'),
(23, 'thanks_message', '<p>Thanks for processing payment . The payment detail is as follow :</p>\r\n<p>[PAYMENT_DETAIL]</p>\r\n<p>Regards,</p>\r\n<p>Administrator Team</p>'),
(24, 'thanks_message_offline', '<p>Thanks for processing the payment. Your payment detail is as follow :</p>\r\n<p>[PAYMENT_DETAIL]</p>\r\n<p> Please send the offline payment ASAP to our bank account . Information of our bank account is as follow :</p>\r\n<p><strong>Tuan Pham Ngoc, Ngan Hang Ngoai Thuong Vietcombank, Account Number XXX045485467</strong></p>\r\n<p>We are looking forward to receiving your payment .</p>'),
(25, 'cancel_message', '<p>You canceled the payment .</p>'),
(26, 'failure_message', '');